version: '3.8'

services:
  app:
    container_name: luck-lottery
    image: your-dockerhub-id/luck-lottery:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - TZ=Asia/Seoul
    restart: always

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

networks:
  backend:
