name: CD

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Set FcmKey
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > src/main/resources/firebase_service_key.json

      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get Short SHA
        id: short_sha
        run: |
          echo "sha_short=$(echo ${{ github.sha }} | head -c 7)" >> $GITHUB_OUTPUT

      - name: Print branch & tag information
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Short SHA: ${{ steps.short_sha.outputs.sha_short }}"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run build
        run: ./gradlew build -x test

      - name: Docker Login and Push
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker build -t $DOCKER_HUB_USERNAME/ohsoontaxi:latest .
          docker push $DOCKER_HUB_USERNAME/ohsoontaxi:latest

      - name: Deploy to EC2 using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/ohsoontaxi
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ohsoontaxi:latest
            sudo docker-compose down
            sudo docker-compose up -d --remove-orphans
